# site settings
title: Brad MacDonald
subtitle: Electrical Engineer
email: bradmacdonald97@gmail.com
description: I'm an electrical engineer focused on embedded systems and computer vision. <br />
baseurl: ""
url: # the base hostname & protocol for your site
author:
street_address: 751 Vandenberg Road
city: King of Prussia
state: PA
zip_code: 19406
country: United States of America
phone: (623) 696-2788

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url:
github_url: https://github.com/Jedibrad
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/brad-m
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
